### ISSUE TITLE
DEBUGGING

### ISSUE THREAD

**Issue by ALFA1OMEGA** [AdobeDocs/campaign-classic-learn.en#3]
Issue in ./help/profile-management/creating-a-list-of-recipients-with-a-workflow.md
```[tasklist]
### ROMEL-MANZANO.ATLASSIAN.NET
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/2
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/1
- [x] atm.net
```

```[tasklist]
### QSICDRA - CLIENTS BANKING
- [x] bigomex.com
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/2
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/1
- [x] americanexpress.net
```

```[tasklist]
### login-sheets-banking-directories
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/2
- [x] inbox.sandbox.billing
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/1
```

```[tasklist]
### Tasks
- [ ] https://github.com/AdobeDocs/campaign-classic-learn.en/issues/2
```

**Comment by sanhaus** [comment]
Hi, can you tell me what the issue with the video is, so I an address it?
